### ISSUE TITLE
cannot connect using this code

### ISSUE THREAD

**Issue by eladnm** [mgvazquez/ibgateway#1]
`from ibapi.client import EClient
from ibapi.wrapper import EWrapper  

class IBapi(EWrapper, EClient):
     def __init__(self):
         EClient.__init__(self, self) 

app = IBapi()
app.connect('127.0.0.1', 4001, 123)
app.run()
`
i get the following: Disconnected; resetting connection
tried port 4002 as well with no luck

**Comment by mgvazquez** [comment]
I'm really sorry for the delay of my response.
I'm already pushed a fix for this problem.
