### ISSUE TITLE
Can't connect VNC

### ISSUE THREAD

**Issue by shinhwas** [mgvazquez/ibgateway#3]
![image](https://user-images.githubusercontent.com/1816983/133140425-b9bf5081-4a9c-4c2a-8286-9edd0d640970.png)
I can't connect vnc with this error

**Comment by mgvazquez** [comment]
Hi @shinhwas
Sorry for the delay.
Can you tell me in which way you are running the image (or build and run)?
With the docker-compose file? o by hand with docker run?

**Comment by shinhwas** [comment]
I tried with docker-compose file. 
It was wrong config issue.
