### ISSUE TITLE
Which port to access in Docker (synology)

### ISSUE THREAD

**Issue by sharepointmike** [mgvazquez/ibgateway#6]
In the docker container I did the following port mapping:

Local port 32778 to container 5900
Local port 32776 to container 4001
My Synology Nas is 192.168.2.6.

When I connect from my local pc using vnc to 192.168.2.6:32778 it works perfectly.

Now, In my Python script I do:

`   from ib_insync import *
    ib = IB()
    ib.connect('192.168.2.6:32776', 4002, clientId=1)`

When I run the script I get "Getaddrinfo failed". 

What can be the issue here?

**Comment by mgvazquez** [comment]
Hi @sharepointmike 
Sorry for the delay.
Can you tell me in which way you are running the image (or build and run)?
With the docker-compose file? o by hand with docker run?
Which config?

**Comment by sharepointmike** [comment]
Solved by doing:
`from ib_insync import * ib = IB() ib.connect('192.168.2.6', 32776, clientId=1)`

Thanks
